/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List containers */
        get: operations["list-containers"];
        put?: never;
        /** Create a container */
        post: operations["create-container"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a container */
        get: operations["get-container"];
        put?: never;
        post?: never;
        /** Delete an empty container */
        delete: operations["delete-container"];
        options?: never;
        head?: never;
        /** Update a container */
        patch: operations["update-container"];
        trace?: never;
    };
    "/containers/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a container and its subtree
         * @description The destination is a room (the container becomes a root of that room) or a container (it becomes a child of it and the whole subtree adopts its room). The move is atomic.
         */
        post: operations["move-container"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List items
         * @description With no filter every item is listed. At most one of room_id and container_id may be set.
         */
        get: operations["list-items"];
        put?: never;
        /** Create an item */
        post: operations["create-item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an item */
        get: operations["get-item"];
        put?: never;
        post?: never;
        /** Delete an item */
        delete: operations["delete-item"];
        options?: never;
        head?: never;
        /** Update an item */
        patch: operations["update-item"];
        trace?: never;
    };
    "/items/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move an item
         * @description The destination is a room or a container; only the location changes.
         */
        post: operations["move-item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rooms */
        get: operations["list-rooms"];
        put?: never;
        /** Create a room */
        post: operations["create-room"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a room */
        get: operations["get-room"];
        put?: never;
        post?: never;
        /** Delete an empty room */
        delete: operations["delete-room"];
        options?: never;
        head?: never;
        /** Update a room */
        patch: operations["update-room"];
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the inventory
         * @description Matches the query against item names, descriptions, aliases and tags, case-insensitively, and returns the matches ordered by name.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContainerDetail: {
            /** Format: date-time */
            created_at: string;
            description: string;
            /**
             * Format: int64
             * @description Container ID.
             */
            id: number;
            /** @example Toolbox */
            name: string;
            /**
             * Format: int64
             * @description ID of the containing container, or empty when the container sits directly in the room.
             */
            parent_id?: number;
            /**
             * @description Location of the container: room and containers from the top down.
             * @example Garage > Toolbox > Drawer 1
             */
            path: string;
            /**
             * Format: int64
             * @description ID of the room the container belongs to.
             */
            room_id: number;
            /** Format: date-time */
            updated_at: string;
        };
        ContainerInput: {
            /** @description Optional description of the container. */
            description?: string;
            /**
             * @description Name of the container, unique within its room.
             * @example Toolbox
             */
            name: string;
            /**
             * Format: int64
             * @description ID of the containing container, or empty when the container sits directly in the room.
             */
            parent_id?: number;
            /**
             * Format: int64
             * @description ID of the room the container sits in.
             */
            room_id: number;
        };
        ContainerPatch: {
            /** @description New description of the container. */
            description?: string;
            /** @description New name of the container. */
            name?: string;
        };
        ContainerResponse: {
            /** Format: date-time */
            created_at: string;
            description: string;
            /**
             * Format: int64
             * @description Container ID.
             */
            id: number;
            /** @example Toolbox */
            name: string;
            /**
             * Format: int64
             * @description ID of the containing container, or empty when the container sits directly in the room.
             */
            parent_id?: number;
            /**
             * Format: int64
             * @description ID of the room the container belongs to.
             */
            room_id: number;
            /** Format: date-time */
            updated_at: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ItemInput: {
            /** @description Other names the item answers to, searched like its name. */
            aliases?: string[] | null;
            /** @description Optional description of the item. */
            description?: string;
            /** @description Where the item lives. */
            location: components["schemas"]["LocationRef"];
            /**
             * @description Name of the item, unique within its location.
             * @example Drill
             */
            name: string;
            /** @description Optional free-form notes. */
            notes?: string;
            /**
             * Format: int64
             * @description How many of the item exist; zero means none left.
             */
            quantity: number;
            /** @description Free-form labels, unique within the item. */
            tags?: string[] | null;
        };
        ItemPatch: {
            /** @description New alias set, replacing the existing one. */
            aliases?: string[];
            /** @description New description of the item. */
            description?: string;
            /** @description New name of the item. */
            name?: string;
            /** @description New notes. */
            notes?: string;
            /**
             * Format: int64
             * @description New quantity.
             */
            quantity?: number;
            /** @description New tag set, replacing the existing one. */
            tags?: string[];
        };
        ItemResponse: {
            aliases: string[] | null;
            /** Format: date-time */
            created_at: string;
            description: string;
            /**
             * Format: int64
             * @description Item ID.
             */
            id: number;
            /** @description Where the item lives. */
            location: components["schemas"]["LocationRef"];
            /** @example Drill */
            name: string;
            notes: string;
            /**
             * Format: int64
             * @example 1
             */
            quantity: number;
            tags: string[] | null;
            /** Format: date-time */
            updated_at: string;
        };
        LocationRef: {
            /**
             * Format: int64
             * @description ID of the room or the container.
             */
            id: number;
            /**
             * @description Whether the location is a room or a container.
             * @enum {string}
             */
            kind: "room" | "container";
        };
        MoveBody: {
            /** @description Where to move the entity. */
            destination: components["schemas"]["LocationRef"];
        };
        RoomInput: {
            /** @description Optional description of the room. */
            description?: string;
            /**
             * @description Name of the room, unique across the inventory.
             * @example Garage
             */
            name: string;
        };
        RoomPatch: {
            /** @description New description of the room. */
            description?: string;
            /** @description New name of the room. */
            name?: string;
        };
        RoomResponse: {
            /**
             * Format: date-time
             * @description When the room was created.
             */
            created_at: string;
            /** @example Cars and tools */
            description: string;
            /**
             * Format: int64
             * @description Room ID.
             */
            id: number;
            /** @example Garage */
            name: string;
            /**
             * Format: date-time
             * @description When the room was last updated.
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-containers": {
        parameters: {
            query?: {
                /** @description Only containers of this room. Zero lists every room. */
                room_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-container": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContainerInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-container": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-container": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-container": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContainerPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "move-container": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-items": {
        parameters: {
            query?: {
                /** @description Only items directly in this room. Zero lists every location. */
                room_id?: number;
                /** @description Only items directly in this container. Zero lists every location. */
                container_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "move-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-room": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-room": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room ID. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-room": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Free-text query. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
